name: Auto Update and Push

on:
  workflow_dispatch:  # 手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download file
        run: wget https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/bogus-nxdomain.china.conf -O bogus-nxdomain.china.conf

      - name: Replace equals sign
        run: sed -e "s|=| |g" bogus-nxdomain.china.conf > bogus-nxdomain.china.smartdns.conf

      - name: Configure Git
        run: |
          git config user.email "13.y@live.com "
          git config user.name "asdfvv"

      - name: Add and commit changes
        run: |
          git add bogus-nxdomain.china.smartdns.conf
          git commit -m "Auto update: Replace equals sign"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.REPO_TOKEN}}
